const FullData = [
  {
    id: 1,
    titleProduct: "Macbooklar",
    designation: "Elektronika",
    taqqoslashuchun: "elektronika",
    mahsulotnomi: "Macbook",
    icontitle: require("../assets/elektronica.png"),
    swiperuchun: require("../assets/mackbook.png"),
    catalogicon: require("../assets/mackbook_catalog.png"),
    namelist: [
      "Mackbook",
      "Noutbooklar",
      "Planshetlar",
      "Telefonlar",
      "iPhonelar",
      "Soatlar",
      "iWatchla",
      "Monitorlarlar",
      "iMaclar",
      "Televizorlar",
    ],
    img: [
      "https://static.re-store.ru/upload/resize_cache/iblock/e7f/100500_800_140cd750bba9870f18aada2478b24840a/gllfdwcxt3b51odg02t1t5robs712837.jpg",
      "https://static.re-store.ru/upload/resize_cache/iblock/597/100500_800_140cd750bba9870f18aada2478b24840a/1kppnkk4c69978vr2hll08oa7s3bxtwd.jpg",
      "https://static.re-store.ru/upload/resize_cache/iblock/52b/100500_800_140cd750bba9870f18aada2478b24840a/8968ni3zx07anriemymfue3yd1o2i6a0.jpg",
    ],
    nameproduct: "Apple MacBook Air 13",
    price: "1000",
    productinfo:
      "(M3, 8C CPU/8C GPU, 2024), 8 ГБ, 256 ГБ SSD, «полуночный черный»",
    nechtaqolgani: 2,
  },

  {
    id: 2,
    titleProduct: "Macbooklar",
    designation: "Elektronika",
    mahsulotnomi: "Macbook",
    taqqoslashuchun: "elektronika",
    icontitle: require("../assets/elektronica.png"),
    swiperuchun: require("../assets/mackbook.png"),
    catalogicon: require("../assets/mackbook_catalog.png"),
    namelist: [
      "Mackbook",
      "Noutbooklar",
      "Planshetlar",
      "Telefonlar",
      "iPhonelar",
      "Soatlar",
      "iWatchla",
      "Monitorlarlar",
      "iMaclar",
      "Televizorlar",
    ],
    img: [
      "https://static.re-store.ru/upload/iblock/30f/72gm7fiyojgepp0or5j8mscav8lv85j5.jpeg",
      "https://static.re-store.ru/upload/iblock/f5f/typi0jkblgto0cv9qt3p20hmio18y18e.jpeg",
      "https://static.re-store.ru/upload/iblock/f24/au3sldpel405gn3vvlkglxlm13a3h2n1.jpeg",
    ],
    nameproduct: "Apple MacBook Air",
    price: "800",
    productinfo: "(M1, 2020) 8 ГБ, 256 ГБ SSD, «серый космос»",
    nechtaqolgani: 5,
  },
  {
    id: 3,
    titleProduct: "Macbooklar",
    designation: "Elektronika",
    mahsulotnomi: "Macbook",
    taqqoslashuchun: "elektronika",
    icontitle: require("../assets/elektronica.png"),
    swiperuchun: require("../assets/mackbook.png"),
    catalogicon: require("../assets/mackbook_catalog.png"),
    namelist: [
      "Mackbook",
      "Noutbooklar",
      "Planshetlar",
      "Telefonlar",
      "iPhonelar",
      "Soatlar",
      "iWatchla",
      "Monitorlarlar",
      "iMaclar",
      "Televizorlar",
    ],
    img: [
      "https://static.re-store.ru/upload/resize_cache/iblock/66f/100500_800_140cd750bba9870f18aada2478b24840a/dsir7jmqrvkd027vqhs4fy7gqlja29z7.jpg",
      "https://static.re-store.ru/upload/resize_cache/iblock/52d/100500_800_140cd750bba9870f18aada2478b24840a/u6gny41d9rzk6tas1hb1oqlz5txucn6r.jpg",
      "https://static.re-store.ru/upload/resize_cache/iblock/852/100500_800_140cd750bba9870f18aada2478b24840a/x40npmq8dbsrod83dfdqzszp3x3pvuoe.jpg",
    ],
    nameproduct: "Apple MacBook Pro 14",
    price: "1500",
    productinfo:
      " (M3 Pro 11C CPU, 14C GPU, 2023) 18 ГБ, 512 ГБ SSD, «чёрный космос»",
    nechtaqolgani: 6,
  },


  {
    id: 6,
    titleProduct: "Macbooklar",
    designation: "Elektronika",
    mahsulotnomi: "Macbook",
    taqqoslashuchun: "elektronika",
    swiperuchun: require("../assets/mackbook.png"),
    icontitle: require("../assets/elektronica.png"),
    catalogicon: require("../assets/mackbook_catalog.png"),
    namelist: [
      "Mackbook",
      "Noutbooklar",
      "Planshetlar",
      "Telefonlar",
      "iPhonelar",
      "Soatlar",
      "iWatchla",
      "Monitorlarlar",
      "iMaclar",
      "Televizorlar",
    ],
    img: [
      "https://static.re-store.ru/upload/resize_cache/iblock/46e/100500_800_140cd750bba9870f18aada2478b24840a/46efe1c754d61d31afb689bbd8f8354c.jpg",
      "https://static.re-store.ru/upload/resize_cache/iblock/e49/100500_800_140cd750bba9870f18aada2478b24840a/e4959a908cd99a14fe1bc34c380c5e85.jpg",
      "https://static.re-store.ru/upload/iblock/83f/83fdad34ea6706669128373ff2c6470f.jpg",
    ],
    nameproduct: "Apple MacBook Air",
    price: "800",
    productinfo: "(M1, 2020) 8 ГБ, 256 ГБ SSD, «серый космос»",
    nechtaqolgani: 1,
  },

  {
    id: 7,
    titleProduct: "Noutbuklar",
    designation: "Elektronika",
    mahsulotnomi: "Noutbuk",
    taqqoslashuchun: "elektronika",
    icontitle: require("../assets/elektronica.png"),
    swiperuchun: require("../assets/noutbok.png"),
    catalogicon: require("../assets/noutbuk__catalog.png"),
    namelist: [
      "Mackbook",
      "Noutbooklar",
      "Planshetlar",
      "Telefonlar",
      "iPhonelar",
      "Soatlar",
      "iWatchla",
      "Monitorlarlar",
      "iMaclar",
      "Televizorlar",
    ],
    img: [
      "https://images.uzum.uz/clljs75enntcj8aa06mg/original.jpg",
      "https://images.uzum.uz/clnfkvlenntcj8aaccsg/original.jpg",
      "https://images.uzum.uz/clnfkvlenntcj8aaccs0/original.jpg",
    ],
    nameproduct: " Acer Aspire 3 15",
    price: "400",
    productinfo: "Core i3-N305 DDR5 8GB SSD 256GB 15.6 FHD",
    nechtaqolgani: 3,
  },
  {
    id: 8,
    titleProduct: "Noutbuklar",
    designation: "Elektronika",
    mahsulotnomi: "Noutbuk",
    taqqoslashuchun: "elektronika",
    icontitle: require("../assets/elektronica.png"),
    swiperuchun: require("../assets/noutbok.png"),
    catalogicon: require("../assets/noutbuk__catalog.png"),
    namelist: [
      "Mackbook",
      "Noutbooklar",
      "Planshetlar",
      "Telefonlar",
      "iPhonelar",
      "Soatlar",
      "iWatchla",
      "Monitorlarlar",
      "iMaclar",
      "Televizorlar",
    ],
    img: [
      "https://images.uzum.uz/cnncc34u2hhlb05hh8qg/original.jpg",
      "https://images.uzum.uz/cnpgtqtod9o9u8o16k70/original.jpg",
      "https://images.uzum.uz/cnpgtqtod9o9u8o16k5g/original.jpg",
    ],
    nameproduct: "Asus Intel N4020",
    price: "300",
    productinfo: " DDR4 4 ГБ / SSD 512 ГБ, 15,6 HD",
    nechtaqolgani: 12,
  },
  {
    id: 9,
    titleProduct: "Aksesuarlar",
    designation: "Aksessuarlar",
    mahsulotnomi: "Ayollar soati",
    taqqoslashuchun: "ayollarsoati",
    icontitle: require("../assets/acsesuar.png"),
    swiperuchun: require("../assets/watch.png"),
    catalogicon: require("../assets/watch__catalog.png"),
    namelist: [
      "Ayollar  aksessuarlari",
      "Ekaklar aksesuarlar",
      "Qizlar uchun aksessuarlar",
      "Og'il bolalar uchun aksessuarlar",
      "Sayohat uchun aksessuarlar",
      "Diniy aksessuarla",
      "Tog' chang'i sport aksessuarlari",
      "Chaqaloqlar  uchun",
    ],
    img: [
      "https://vetervremeni.uz/wp-content/uploads/2021/06/t035.207.26.031.00-tissot.jpg",
      "https://vetervremeni.uz/wp-content/uploads/2021/06/t.035.207.26.031.00-tissot.jpg",
      "https://vetervremeni.uz/wp-content/uploads/2021/06/tissot.jpg",
    ],
    nameproduct: "Tissot T-Classic",
    price: "400",
    productinfo: "T035.207.26.031.00",
    nechtaqolgani: 2,
  },
  {
    id: 10,
    titleProduct: "Kitoblar",
    designation: "Kitoblar",
    mahsulotnomi: "Badiy adabiyot",
    taqqoslashuchun: "badiyadabiyot",
    icontitle: require("../assets/book.png"),
    swiperuchun: require("../assets/book.png"),
    catalogicon: require("../assets/book__catalog.png"),
    namelist: [
      "Badiy adabiyot",
      "Biznes adabiyot",
      "Bolalarga va ota-onalarga",
      "Bukinistika",
      "Chet tillaridagi-adabiyotlar",
      "Diniy kitoblar",
      "Elektron audio kitoblar",
      "Chaqaloqlar  uchun",
    ],
    img: [
      "https://assets.asaxiy.uz/product/items/desktop/69f268fb2ba1068615b3219c6e8f57e82022042615260587017FE782Vt8Uy.jpg.webp",
      "https://assets.asaxiy.uz/product/items/desktop/b7ee0d0d4d5ef995aae0fc691e6d840d2022042615273751372APKwbYVRkK.jpg.webp",
    ],
    nameproduct: "Abdulla Avloniy",
    price: "6.5",
    productinfo: "Abdulla avloniy namoyendalari",
    nechtaqolgani: 2,
  },
  {
    id: 11,
    titleProduct: "Avtotovarlar",
    designation: "Avtotovarlar",
    mahsulotnomi: "Avto akumlyator",
    taqqoslashuchun: "avtoakumlayotrlar",
    icontitle: require("../assets/auto.png"),
    swiperuchun: require("../assets/accumlayator.png"),
    catalogicon: require("../assets/accumlayator__catalog.png"),

    namelist: [
      "Akkumlyatorlar",
      "Aksessuarlar",
      "Asboblar va uskunalar",
      "Avtomobil extiyot qisimlar",
      "Avtomobil uchun elektornika",
      "Moylar va kimyoviy moddalar",
      "Avtotovush",
      "Shinalar va diskalar",
    ],
    img: [
      "https://images.prom.ua/2354953491_w640_h640_2354953491.jpg",
      "https://images.prom.ua/1531637591_w640_h640_1531637591.jpg",
      "https://images.prom.ua/1531637866_w640_h640_1531637866.jpg",
    ],
    nameproduct: "АКУМУЛЯТОР MORATTI 60AH",
    price: "6.5",
    productinfo: " L, EN 600, АВТОМОБІЛЬНИЙ. ПРАЦЮЄМО З ПДВ",
    nechtaqolgani: 18,
  },
  {
    id: 12,
    titleProduct: "Maishiy texnika",
    designation: "Maishiy texnika",
    mahsulotnomi: "Konditsioner",
    taqqoslashuchun: "iqlimtexnikasi",
    icontitle: require("../assets/maishiy__texnika.png"),
    swiperuchun: require("../assets/airconditioner.png"),
    catalogicon: require("../assets/airconditioner__catalog.png"),
    namelist: [
      "Iqlim texnikasi",
      "Katta maishiy texnika",
      "Asboblar va uskunalar",
      "Oshxona texnikalari",
      "Avtomobil uchun elektornika",
      "Uy uchun texnika",
    ],
    img: [
      "https://minio.alifshop.uz/shop/products/B3QbA9cOxbVkuQbblT6nv5c6VcmhSCra16hJOO8n.webp",
      "https://minio.alifshop.uz/shop/products/Njq9MUcM5FKJyODyYmk7eHPbR88eztWYzYkuFncJ.jpg",
    ],
    nameproduct: "Кондиционер Artel Grand",
    price: "50.6",
    productinfo: " Art-12HDI, серый",
    nechtaqolgani: 22,
  },
  {
    id: 13,
    titleProduct: "Hayvonlar uchun tovarlar",
    designation: "Hayvonlar uchun tovarlar",
    mahsulotnomi: "Baliq ozuqasi",
    taqqoslashuchun: "baliqozuqasi",
    icontitle: require("../assets/animal.png"),
    swiperuchun: require("../assets/baliq.png"),
    catalogicon: require("../assets/animal__catalog.png"),
    namelist: [
      "Baliqlar uchun",
      "Gigiyena ",
      "Itlar uchun",
      "Kemiruvchilar uchun",
      "Qushlar uchun",
      "Vetapteka",
    ],
    img: ["https://charley.uz/d/160880648_w640_h640_tetra-variety-sticks.webp"],
    nameproduct: "Tetra Pond Variety Sticks",
    price: "2.5",
    productinfo: " Корм для всех прудовых рыб Пакетик 100 гр",
    nechtaqolgani: 3,
  },
  {
    id: 14,
    titleProduct: "Poyabzallar",
    designation: "Poyabzallar",
    mahsulotnomi: "Ayolla tuflisi",
    taqqoslashuchun: "baliquchuntaom",
    icontitle: require("../assets/poyabzallar.png"),
    swiperuchun: require("../assets/jen__tufli.png"),
    catalogicon: require("../assets/poyabzallar__catalog.png"),
    namelist: [
      "Ayollar poyabzali",
      "Erkaklar poyabzali ",
      "Qizlar uchun poyabzallar",
      "O'gil bolalar uchun poyabzallar",
    ],
    img: [
      "https://images.uzum.uz/cnu4cgn2u18gghckvnc0/original.jpg",
      "https://images.uzum.uz/cnu4cgn2u18gghckvncg/original.jpg",
    ],
    nameproduct: "Женские кожанные туфли",
    price: "80",
    productinfo: " На каблуке",
    nechtaqolgani: 4,
  },
];

export default FullData;
